#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &

bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
